name: imthinker::net
description: "Yet another Ryutaro Miyashita"
url: "http://imthinker.net"
markdown: redcarpet
highlighter: pygments
safe: true
lsi: false
layout: null
exclude: ["vendor", "Gemfile", "Gemfile.lock"]
